# Generated by Django 4.1.3 on 2022-11-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cnab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("Débito", "One"),
                            ("Boleto", "Two"),
                            ("Financiamento", "Three"),
                            ("Crédito", "Four"),
                            ("Recebimento Empréstimo", "Five"),
                            ("Vendas", "Six"),
                            ("Recebimento TED", "Seven"),
                            ("Recebimento DOC", "Eight"),
                            ("Aluguel", "Nine"),
                        ],
                        max_length=25,
                    ),
                ),
                ("date", models.CharField(max_length=8)),
                ("value", models.CharField(max_length=10)),
                ("cpf", models.CharField(max_length=11)),
                ("card", models.CharField(max_length=12)),
                ("hour", models.CharField(max_length=6)),
                ("name_owner", models.CharField(max_length=14)),
                ("name_company", models.CharField(max_length=19)),
            ],
        ),
    ]
